- rubocop.yml
- allow redundant return -> allow some clarity
- enforce `return` in stead of `return nil`
Something else right now? @ccyrille, @hugobarthelemy
> Update rubocop rules

- rubocop.yml
Let's discuss this together :)
* Customize Rubocop numeric predicate style rule : enforce the `> 0` syntax instead of `positive?`. To be discussed.
* Reorder rules alphabetically (and remove some optional statements)
> Customize Rubocop numeric predicate

- rubocop.yml
Usually, compact style is preferable but there are very good reasons to use nested style, for example when writing a standalone Ruby script.
If we force compact style in a standalone file, the following code :
```Ruby
module Lambda
class TerraformApplyPlan
end
end
```
will have to become (module have to be declared first) : 
```Ruby
module Lambda
end
class Lambda::TerraformApplyPlan
end
```
... which doesn't seem really nice 😉
> disable Rubocop Style/ClassAndModuleChildren check

- rubocop.yml
https://github.com/klaxit/ruby/blob/3920aa8f72433cb0080934049b5f2aa23ef9b853/rubocop.yml#L85-L91
I personally hate this rule because it forces me to think about which quotes I should use. If enforced, we'll just always use double quotes.
👍 👎 ?
> Enforce double quotes in string interpolation

- rubocop.yml
As discussed before, the `rubocop` rule `Layout/EmptyLineAfterGuardClause` does not reach a consensus amongst us. 
For example, I am still frustrated with not beeing able to let it "as is" : 
```ruby
def home_loc
return nil if home_lat.nil? || home_lng.nil?
Loc::Location[home_lat, home_lng]
end
```
I think it is best that we disable this rule and let each one of us what is best for the things he works on.
> Disable Layout/EmptyLineAfterGuardClause rule

- danger-klaxit/Gemfile.lock
- danger-klaxit/lib/danger_plugin.rb
- danger-klaxit/lib/klaxit/gem_version.rb
- danger-klaxit/spec/klaxit_spec.rb
Our api encountered an issue with the public methods definition (see ci for https://github.com/klaxit/klaxit-api/pull/954). This should do the trick.
> Avoid crashing when there is no class to test

- danger-klaxit/Gemfile.lock
- danger-klaxit/danger-klaxit.gemspec
- danger-klaxit/lib/danger_plugin.rb
- danger-klaxit/lib/klaxit/gem_version.rb
This PR will allow a less verbose bot. However, it needs the merge and deployment of https://github.com/ashfurrow/danger-rubocop/pull/30.
And since a gemspec file [cannot have a git branch dependency](https://stackoverflow.com/a/6499472/6320039), for now on the hack for using it it to add this to gemfiles using klaxit danger:
```ruby
gem "danger-rubocop", github: "klaxit/danger-rubocop", branch: "force-only_report_new_offences"
```
Add of course `bundle update danger-rubocop`.
> Only report new offenses

- danger-klaxit/lib/danger_plugin.rb
- danger-klaxit/lib/klaxit/gem_version.rb
- danger-klaxit/spec/klaxit_spec.rb
Avoid messages such as:
> ⚠️ No spec found for file db/migrate/20190907421053_you_will_not_know.rb.
We want to check for missing specs only in files that RuboCop would check in our project. 
The non-trivial part was running into RuboCop source code to
get the config generation:
```ruby
rubocop_config = RuboCop::ConfigStore.new.for(".")
```
A best solution would be to have rubocop check for missing specs itself!
> Exclude file unchecked by rubocop from spec verification

- danger-klaxit/Gemfile.lock
- danger-klaxit/lib/danger_plugin.rb
- danger-klaxit/lib/klaxit/gem_version.rb
- danger-klaxit/spec/klaxit_spec.rb
Fixes danger for klaxit/klaxit-api#968. You can take a peak at the new non-regression spec for more details.
> Avoid crash when there is a `class << self` with only one method

- rubocop.yml
See [this so post](https://stackoverflow.com/a/58220572/6320039) for details!
The annoying warning is:
> klaxit-rubocop: Warning: no department given for Documentation.
> Avoid warning _No department given for XXX_

- rubocop.yml
The rubocop rule [`Style/NegatedIf`][rule] can sometimes generate code harder to understand with `unless` than with `if`:
```ruby
do_stuff unless var.nil? # reads _do stuff unless var is nil_
do_stuff if !var.nil? # reads _do stuff if var is not nil_  which is clearer IMHO
```
Discussing it with @ThomasKlaxit, we both write `if` condition first, then negate it, then write `unless`, which is a no-brainer. I think that it may look prettier, but is harder to grasp.
What is your opinion about that? (👍 👎, or detailed answer!)
[rule]: https://rubocop.readthedocs.io/en/latest/cops_style/#stylenegatedif
> rubocop: Disable Style/NegatedIf

- rubocop.yml
In most of my pull requests I ask for usage of:
```ruby
foo = "text"
```
rather than:
```ruby
foo = "text".freeze
```
Moreover, this as great chances of being a default behavior in the next ruby major, and is a better behavior (IMO).
Lastly, the default behavior of this rule allows to **not use frozen strings** by using the top comment with a `false` value.
All that said, I suggest we go back to the default setting of [Style/FrozenStringLiteralComment][rule].
What is your opinion ? React 👍 👎or detail your answer!
[rule]: https://rubocop.readthedocs.io/en/stable/cops_style/#stylefrozenstringliteralcomment
> Enforce `frozen_string_literal` comment usage

- rubocop.yml
Since, we'are adding Yardoc support to our codebase (https://github.com/klaxit/klaxit-otp-master/pull/115), this PR is for enabling `Style/DocumentationMethod` rubocop rule to force method documenting.
> Enforce method documentation

- rubocop-klaxit/rubocop-klaxit.gemspec
**Rename `ruby-klaxit` to `rubocop-klaxit`** 🖍
The gem was originally to include all subjects. Now that it only manages Rubocop, it seems more logical to rename it to rubocop-klaxit.
> Feature: Rename ruby-klaxit to rubocop-klaxit

- rubocop-klaxit/rubocop-klaxit.gemspec
> **More lax on rubocop version** 🚦
> We can be more lax about the version of Rubocop used. This will allow us to have fewer conflicts.
> Fix: More lax on rubocop version

- danger-klaxit/danger-klaxit.gemspec
- danger-klaxit/lib/klaxit/danger/gem_version.rb
- danger-klaxit/lib/klaxit/gem_version.rb
- rubocop-klaxit/lib/klaxit/rubocop/gem_version.rb
- rubocop-klaxit/rubocop-klaxit.gemspec
Use different namespaces for gem versions.
Without this, when you use both gems in a project, it redefines the `Klaxit::VERSION` constant and causes problems with bundler & cache.
> fix Klaxit::VERSION namespace clash

- rubocop-klaxit/Gemfile
- rubocop-klaxit/Gemfile.lock
- rubocop-klaxit/cops/active-record/update_attribute.rb
- rubocop-klaxit/rubocop.rb
- rubocop.yml
**Rubocop: Add Rails/SaveBang cop** 👮‍♀️
Add Rubocop warning on the bang-free ActiveRecord persistences methods when they are used.
Also added a rule on the use of `update-attribute` method, instead of `update_column`.
> Feature: Add Rails/SaveBang rubocop cop

- danger-klaxit/Gemfile.lock
- danger-klaxit/README.md
- danger-klaxit/danger-klaxit.gemspec
- danger-klaxit/lib/danger_plugin.rb
- danger-klaxit/lib/klaxit/danger/gem_version.rb
- danger-klaxit/spec/klaxit_spec.rb
- danger-klaxit/spec/support/fixtures/klaxit-example-app/app/models/user.rb
Now `klaxit.common` has brakeman power. This will work only if a rails app is detected (if there is an `app/` folder).
You can see a preview in klaxit/klaxit-matcher#371.
> Add `run_brakeman_scanner` command to danger

- danger-klaxit/lib/danger_plugin.rb
- danger-klaxit/spec/klaxit_spec.rb
Following the fix https://github.com/presidentbeef/brakeman/pull/1506, we no longer need to force the version of Rails for Sinatra projects. Brakeman can now use the ActiveRecord version instead.
Revert of commit https://github.com/klaxit/ruby/pull/35/commits/3cff8d2699ee3a67c03d97c6c3eb5ecc02aa7ac9
> Remove fix: Force Rails version for Brakeman when in a Sinatra project

- danger-klaxit/README.md
- danger-klaxit/lib/danger_plugin.rb
- danger-klaxit/spec/klaxit_spec.rb
Add method to check structure.sql/schema.rb and migrations:
- Verify that structure.sql or schema.rb is updated when migrations are added
- Verify structure.sql contains timestamps of new migrations
- Verify schema.rb contains timestamp of last migration
> Check structure.sql and schema.sql

- rubocop.yml
There seems to be a problem with the https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/IfUnlessModifier rule preventing having a `if/unless` statement on multiple lines. This one doesn't take into account the default maximum line size value to allow a multi-line statement.
By explicitly adding this limit, the cop is correctly applied and is disabled if the inlined expression exceeds the limit.
> Fix: force the character limit per line

- danger-klaxit/lib/danger_plugin.rb
- danger-klaxit/spec/klaxit_spec.rb
We don’t want to raise alert if we add new `workers/migrations` without `spec` file.
> Feat - Danger config exclude workers/migrations new file spec

- rubocop.yml
We want to use Style/MutableConstant strict rule
https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/MutableConstant
By default we already had literals version.
> Feat - Use Style/MutableConstant strict rule

- danger-klaxit/lib/klaxit/config_sorter.rb
The word diff format is not correctly understood by GitHub Markdown,
hence a simple diff is just clearer.
```diff
diff --git a/config/config.yml b/blop
index 9fff68e6e..b451d214f 100644
--- a/config/config.yml
+++ b/blop
@@ -110,8 +110,8 @@ DEFAULTS: &DEFAULTS
sidekiq_status_expiration:         <%= (ENV["SIDEKIQ_STATUS_EXPIRATION"] || 900).to_i %>
sidekiq_supervision_pool_size:     <%= ENV["SIDEKIQ_SUPERVISION_POOL_SIZE"] %>
silent_notification_prefix:        <%= ENV["SILENT_NOTIFICATION_PREFIX"] || "SILENT --" %>
[-  slack_ops_channel:                 <%= ENV["SLACK_OPS_CHANNEL"] %>-]
slack_oauth_token:                 <%= ENV["SLACK_OAUTH_TOKEN"] %>
{+slack_ops_channel:                 <%= ENV["SLACK_OPS_CHANNEL"] %>+}
snitch_mailchimp_update_all_ended: <%= …
```
> Fix config_sorter diff

- rubocop-klaxit/cops/active-record/no_transaction_on_add_index_migration.rb
- rubocop-klaxit/rubocop.rb
- rubocop-klaxit/spec/cops/active-record/no_transaction_on_add_index_migration_spec.rb
Add new rule to ensure migrations that add indexes come outside of transactions with `disable_ddl_migration!`. This is to ensure that there will be no downtime when deploying.
> Ensure migrations with add_index has disable_ddl_migration!

- danger-klaxit/danger-klaxit.gemspec
- rubocop-klaxit/rubocop-klaxit.gemspec
- rubocop.yml
Bump version dependencies to be able to use new RuboCop functionalities in AST node matching.
> Bump gem versions

- danger-klaxit/lib/danger_plugin.rb
- danger-klaxit/spec/klaxit_spec.rb
For `fail_for_not_updated_structure_sql `rule, ignore non-ruby files in migration folder.
This allow us to add fixtures without a danger error.
> Only check ruby files in migration folder

- danger-klaxit/lib/danger_plugin.rb
- danger-klaxit/spec/klaxit_spec.rb
Timestamps are not parsed correctly due to usage of `rpartition` rather than `partition`, due to spaces represented as underscores as well in migration filenames.
> Fix migration timestamp parsing

- danger-klaxit/lib/danger_plugin.rb
Validation fails when `structure.sql` is added and not modified. This PR fixes this.
> Fix failed validation when passing from schema.rb to structure.sql
